version: '3'  # version of compose format 

services:
  web-service:
    build: ./web  # path is relative to docker-compose.yml localtion
    volumes:
      - ./web:/usr/src/app # mount point
    ports:
      - 5001:80  # host:container
    links:
      - "gray_service:gr"
      - "sharp_service:sh"
      - "blur_service:bl"
      - "edge_service:ed"
      - "saliency_service:sa"
    command: pip install -r requirements.txt
    command: python3 -u app.py
    

  gray_service:
    build: ./gray  # path is relative to docker-compose.yml localtion
    volumes:
      - ./gray:/usr/src/app # mount point
    ports:
      - 5002:80  # host:container
    command: pip install -r requirements.txt
    command: python3 -u gray_app.py

  sharp_service:
    build: ./sharp  # path is relative to docker-compose.yml localtion
    volumes:
      - ./sharp:/usr/src/app # mount point
    ports:
      - 5003:80  # host:container
    command: pip install -r requirements.txt
    command: python3 -u sharp_app.py

  blur_service:
    build: ./blur  # path is relative to docker-compose.yml localtion
    volumes:
      - ./blur:/usr/src/app # mount point
    ports:
      - 5004:80  # host:container
    command: pip install -r requirements.txt
    command: python3 -u blur_app.py

  edge_service:
    build: ./edge  # path is relative to docker-compose.yml localtion
    volumes:
      - ./edge:/usr/src/app # mount point
    ports:
      - 5005:80  # host:container
    command: pip install -r requirements.txt
    command: python3 -u edge_app.py

  saliency_service:
    build: ./saliency  # path is relative to docker-compose.yml localtion
    volumes:
      - ./saliency:/usr/src/app # mount point
    ports:
      - 5006:80  # host:container
    command: pip install -r requirements.txt
    command: python3 -u saliency_app.py 
