version: '3'  # version of compose format 

services:
  web-service:
    build: ./web  # path is relative to docker-compose.yml localtion
    volumes:
      - ./web:/usr/src/app # mount point
    ports:
      - 5001:80  # host:container
    links:
      - "text_detection_service:tds"
      - "text_preprocessing_service:tps"
      - "text_recognition_service:trs"
    command: pip install -r requirements.txt
    command: python3 -u app.py
    

  text_detection_service:
    build: ./detection  # path is relative to docker-compose.yml localtion
    volumes:
      - ./detection:/usr/src/app # mount point
    ports:
      - 5002:80  # host:container
    command: pip install -r requirements.txt
    command: pip install shapely
    command: apt-get install libgeos-dev
    command: python3 -u detection_app.py

  text_preprocessing_service:
    build: ./preprocess  # path is relative to docker-compose.yml localtion
    volumes:
      - ./preprocess:/usr/src/app # mount point
    ports:
      - 5003:80  # host:container
    command: pip install -r requirements.txt
    command: python3 -u preprocess_app.py

  text_recognition_service:
    build: ./recognition  # path is relative to docker-compose.yml localtion
    volumes:
      - ./recognition:/usr/src/app # mount point
    ports:
      - 5004:80  # host:container
    command: pip install -r requirements.txt
    command: python3 -u recognition_app.py